import { chromium } from 'playwright';
const browser = await chromium.launch({ args: ['--use-fake-device-for-media-stream', '--use-fake-ui-for-media-stream'] });
const ctx = await browser.newContext({ viewport: { width: 390, height: 844 }, deviceScaleFactor: 2, permissions: ['camera', 'microphone'] });
const page = await ctx.newPage();
const errors = [];
page.on('pageerror', e => errors.push(e.message));
page.on('console', m => { if (m.type() === 'error') errors.push(m.text()); });
const check = (c, msg) => { console.log((c ? '  ✓ ' : '  ✗ ') + msg); if (!c) errors.push('FAILED: ' + msg); };
// QR deep link: legacy param names from the old README still work
await page.goto((process.env.GYMOS_URL || 'http://127.0.0.1:8765/') + '?exercise=dumbbell-curl&weight=20&reps=5&sets=2&rest=15', { waitUntil: 'networkidle' });
await page.evaluate(() => { Spotter.DB.onboarded = true; });
const setup = await page.evaluate(() => ({ screen: document.querySelector('.screen.active').id, name: document.getElementById('setup-name').textContent, banner: !!document.querySelector('#setup-banner .banner'), plan: Spotter.W.plan, url: location.search }));
check(setup.screen === 'setup' && setup.name === 'Dumbbell curl' && setup.banner, 'QR link opens curl setup with banner');
check(setup.plan.reps === 5 && setup.plan.sets === 2 && setup.plan.weight === 20 && setup.plan.rest === 15, 'QR link fills sets, reps, weight, rest');
check(setup.url === '', 'QR params cleared from the address bar');
await page.click('#start-btn');
await page.waitForFunction(() => Spotter.W.mode === 'check', null, { timeout: 90000 });
await page.evaluate(() => { Spotter.W.testHold = true; });
// Feed simulated frames through the real pipeline
const feed = async (plan, t0) => page.evaluate(([plan, t0]) => {
  const G = window.GymEngine, ex = G.byId('curl');
  const frames = G.sim.stream(ex, plan, { noise: 1, t0 });
  frames.forEach(f => Spotter.feed(f));
  return frames.length ? frames[frames.length - 1].t : t0;
}, [plan, t0]);
const hold = (d, a) => ({ dur: d, hold: true, from: { left: a, right: a }, to: { left: a, right: a } });
const rep = (s, f, out = 1, back = 1.3) => [{ dur: out, from: { left: s, right: s }, to: { left: f, right: f } }, { dur: back, from: { left: f, right: f }, to: { left: s, right: s } }, hold(0.3, s)];
let t = 100000;
t = await feed([hold(1.5, 150)], t);
check(await page.evaluate(() => Spotter.W.mode) === 'calibrate', 'position check passes and asks for warm-up reps');
t = await feed([...rep(150, 70, 2, 2), ...rep(150, 70, 2, 2), hold(0.5, 150)], t);
const cal = await page.evaluate(() => Spotter.DB.calib.curl);
check(cal && Math.abs(cal.open - 150) < 8 && Math.abs(cal.closed - 70) < 8, 'calibration learned 150°→70° (got ' + (cal && cal.open) + '/' + (cal && cal.closed) + ')');
await page.waitForFunction(() => Spotter.W.mode === 'lift', null, { timeout: 5000 });
t = await feed([hold(0.5, 150), ...Array.from({ length: 5 }, () => rep(150, 72)).flat(), hold(4.5, 150)], t);
const afterSet1 = await page.evaluate(() => ({ screen: document.querySelector('.screen.active').id, sets: Spotter.W.sets.length, reps: Spotter.W.sets[0] && Spotter.W.sets[0].reps, last: document.getElementById('rest-last').textContent }));
check(afterSet1.screen === 'rest' && afterSet1.reps === 5, 'set 1: 5 reps counted with learned range, auto-ended into rest (' + JSON.stringify(afterSet1) + ')');
await page.screenshot({ path: (process.env.SHOTS || './shots/') + '60-rest.png' });
await page.click('#rest-skip');
check(await page.evaluate(() => Spotter.W.mode === 'lift' && Spotter.W.set === 2), 'skip rest starts set 2');
t = await feed([hold(0.5, 150), ...Array.from({ length: 4 }, (_, i) => rep(150, 72, 1 + i * 0.5)).flat(), ...rep(150, 110), hold(9, 150)], t);
await page.waitForFunction(() => document.querySelector('.screen.active').id === 'summary', null, { timeout: 5000 }).catch(() => {});
const sum = await page.evaluate(() => ({ screen: document.querySelector('.screen.active').id, saved: Spotter.DB.sessions.length, s: Spotter.DB.sessions[0] }));
check(sum.screen === 'summary' && sum.saved === 1, 'workout saved and summary shown');
check(sum.s && sum.s.sets[1].reps === 4 && sum.s.sets[1].partials === 1, 'set 2: 4 reps + 1 partial (half rep not counted)');
check(sum.s && sum.s.rec && sum.s.rec.weight === 20, 'missed target → recommendation holds weight (' + (sum.s && sum.s.rec.note) + ')');
await page.screenshot({ path: (process.env.SHOTS || './shots/') + '61-summary-real.png' });
await page.click('#sum-done');
const home = await page.evaluate(() => document.querySelector('.ex-row[data-id="curl"] .meta').textContent);
check(/20 lb/.test(home), 'home shows last session for curl: ' + home);
await page.evaluate(() => Spotter.show('history'));
await page.screenshot({ path: (process.env.SHOTS || './shots/') + '62-history.png' });
check(await page.evaluate(() => document.querySelectorAll('.hist-row').length) === 1, 'history lists the workout');
// Reload: data persisted
await page.reload({ waitUntil: 'networkidle' });
check(await page.evaluate(() => Spotter.DB.sessions.length === 1 && !!Spotter.DB.calib.curl), 'history and learned range survive a reload');
console.log(errors.length ? 'ERRORS:\n' + errors.join('\n') : 'NO ERRORS');
await browser.close();
